name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Const-Team/Document
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist/
        COMMIT_MESSAGE: 'Auto deploy from Github Actions'
        CNAME: fe.const.team

    - name: repo-sync
      uses: yehan-coding/yehan-git-sync@v1
      with:
        source_repo_url: git@github.com:Const-Team/Document.git
        source_branch: master
        destination_repo_url: git@e.coding.net:wangdaodao/document/document.git
        destination_branch: master
        ssh_private_key: ${{ secrets.CODING_SSH_PRIVATE_KEY }}